/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nihao' at '17-5-22 下午7:41' with Gradle 2.11
 *
 * @author nihao, @date 17-5-22 下午7:41
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
